---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: frontend-depl
    name: frontend-depl
spec:
    replicas: {{ .Values.service.frontend.replicas }}
    selector:
        matchLabels:
            app: frontend-pod
    template:
        metadata:
            labels:
                app: frontend-pod
            name: frontend-pod
        spec:
            containers:
                - name: frontend-app
                  command: ["/bin/bash", "-c", "nodemon -L /var/www/app/index.js"]
                  image: bluetechy/frontend-app
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  ports:
                      - containerPort: 8080
                  {{- if .Values.deployment.local }}
                  volumeMounts:
                      - name: frontend-volume-src
                        mountPath: "/var/www/app"
                  {{- end }}
            {{- if .Values.deployment.local }}
            volumes:
                - name: frontend-volume-src
                  hostPath:
                      path: "{{ .Values.repository.rootDir }}/services/frontend-app/src"
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-svc
spec:
    selector:
        app: frontend-pod
    ports:
        - name: frontend-port-ingress
          port: 48080
          protocol: TCP
          targetPort: 8080
    type: LoadBalancer
